# Generated by Django 5.2.13 on 2026-06-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProducerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_name", models.CharField(max_length=150)),
                ("contact_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=30)),
                ("business_address", models.TextField()),
                ("postcode", models.CharField(max_length=12)),
                ("role", models.CharField(default="producer", editable=False, max_length=30)),
                ("verified", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["business_name"],
            },
        ),
    ]
