# Generated by Django 5.2.13 on 2026-07-04 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_customerprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("unit", models.CharField(max_length=40)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("in_season", "In Season"),
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("out_of_season", "Out of Season"),
                        ],
                        default="in_season",
                        max_length=30,
                    ),
                ),
                ("stock_quantity", models.DecimalField(decimal_places=2, max_digits=9)),
                ("allergen_info", models.CharField(blank=True, max_length=255)),
                ("harvest_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="marketplace.category",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="marketplace.producerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
