# Generated by Django 5.2.13 on 2026-07-06 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_order_special_instructions_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="certification_body",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="certification_number",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="product",
            name="organic_certified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="WeeklySettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                (
                    "total_order_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "producer_payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_bank_transfer", "Pending Bank Transfer"),
                            ("processed", "Processed"),
                        ],
                        default="pending_bank_transfer",
                        max_length=30,
                    ),
                ),
                ("reference", models.CharField(max_length=40, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "orders",
                    models.ManyToManyField(
                        blank=True,
                        related_name="weekly_settlements",
                        to="marketplace.order",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_settlements",
                        to="marketplace.producerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("producer", "week_start"),
                        name="unique_weekly_settlement_per_producer",
                    )
                ],
            },
        ),
    ]
